name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv install --dev --python `which python`

      - id: make
        name: Run make command
        run: |
          pipenv run python setup.py install
          make scrape
        shell: bash

      - id: commit
        name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git add ./
          git commit -m "Scrape" && git push || true
        shell: bash
